name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clonación del Repositorio
    - name: Checkout repository
      uses: actions/checkout@v2

    # Instalación de Dependencias
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install

    # Pruebas Unitarias
    - name: Run tests
      run: npm test -- --watchAll=false

    # Generar informes de cobertura (opcional)
    - name: Generate coverage report
      run: npm test -- --coverage

    # Subir informe de cobertura a Codecov (opcional)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
